server:
  port: 9998
spring:
    datasource:
        name: springboot-shiro2
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/marvel
        username: root
        password: root


    ## Redis 配置
    redis:
      ## Redis数据库索引（默认为0）
      database: 0
      ## Redis服务器地址
      host: 127.0.0.1
      pool:
        ## 连接池中的最大空闲连接
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ## 连接池中的最小空闲连接
        min-idle: 0
        ## 连接超时时间（毫秒）
      timeout: 0
      ## Redis服务器连接端口
      port: 6379
