
spring:
    datasource:
        name: marvel
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/marvel
        username: root
        password: root

server:
  port: 8899