spring:
    datasource:
        name: fire_ads
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.94.172.234:3306/fire_ads
        username: root
        password: root
    dubbo:
        application:
            name: springboot-dubbo-xml
        registry:
           address: zookeeper://47.94.172.234:2181
        protocol:
            name: dubbo
            port: 20880
server:
  port: 8989

